/** Native Actions matrix executable and trusted serial aggregate composition. */
import { canonicalStringify } from "../contracts/canonical.ts";
import {
  type MatrixCellGrantV1,
  type MatrixCellResultV1,
  matrixDigestV1,
  type MatrixPlanV1,
  MAX_MATRIX_ARTIFACT_BYTES,
  tryParseMatrixPlanV1,
} from "../contracts/matrix.ts";
import type { RepositoryConfigV1 } from "../contracts/repository-config.ts";
import { createRunBounds, type RepairCycleDepsV1 } from "../repair/loop.ts";
import {
  type ActionsRepairHostDepsV1,
  type ActionsTargetCyclesInputV1,
  type ActionsTargetCyclesResultV1,
  childRunDeadlineV1,
  runActionsRepairHost,
  runActionsTargetCycles,
} from "./actions.ts";
import {
  ingestMatrixResults,
  type MatrixPlanReportV1,
  runMatrixCell,
  runMatrixPlanEntrypoint,
} from "./matrix.ts";
import {
  createGitBundleExporter,
  createGitBundleImporter,
} from "./matrix-git.ts";
import type { MatrixArtifactTransportV1 } from "./matrix-artifact-port.ts";

export interface MatrixNativeCarrierV1 {
  /** Digest supplied by native needs.matrix_plan.outputs, outside artifact contents. */
  planDigest: string;
  /** Native matrix cell selection; absent in the serial aggregate job. */
  cellId?: string;
}
export interface ActionsMatrixHostDepsV1 extends ActionsRepairHostDepsV1 {
  carrier?: MatrixNativeCarrierV1;
  artifactTransport?: MatrixArtifactTransportV1;
}
function parseCarrier(value: unknown, cell: boolean): MatrixNativeCarrierV1 {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error("matrix native output carrier is malformed");
  }
  const record = value as Record<string, unknown>;
  if (
    Object.keys(record).some((key) =>
      key !== "planDigest" && key !== "cellId"
    ) ||
    typeof record.planDigest !== "string" ||
    !/^[0-9a-f]{64}$/.test(record.planDigest) ||
    (record.cellId !== undefined &&
      (typeof record.cellId !== "string" ||
        !/^[0-9a-f]{64}$/.test(record.cellId))) ||
    (cell && record.cellId === undefined)
  ) {
    throw new Error("matrix native output carrier is malformed");
  }
  return record as unknown as MatrixNativeCarrierV1;
}
/** Standard input is generated by the fixed workflow from native needs/matrix outputs. */
export async function readMatrixNativeCarrier(
  cell: boolean,
  allowEmpty = false,
): Promise<MatrixNativeCarrierV1 | undefined> {
  const bytes: Uint8Array[] = [];
  let size = 0;
  for await (const part of Deno.stdin.readable) {
    size += part.length;
    if (size > 4096) {
      throw new Error("matrix native output carrier is oversized");
    }
    bytes.push(part);
  }
  if (size === 0 && allowEmpty) return undefined;
  const joined = new Uint8Array(size);
  let offset = 0;
  for (const part of bytes) {
    joined.set(part, offset);
    offset += part.length;
  }
  return parseCarrier(JSON.parse(new TextDecoder().decode(joined)), cell);
}
function hostOf(input: ActionsTargetCyclesInputV1) {
  if (input.host === undefined) {
    throw new Error("matrix host assembly is unavailable");
  }
  return input.host;
}
function targetDeps(
  input: ActionsTargetCyclesInputV1,
  config: RepositoryConfigV1,
): RepairCycleDepsV1 {
  return {
    clock: input.clock,
    state: input.state,
    configs: input.configs,
    controllerSha: input.controllerSha,
    github: input.composeGithub(config),
    githubCooldown: input.githubCooldown,
    incidents: input.incidents,
    replay: input.replay,
    model: input.model,
    budget: input.budget,
    externalImplementations: true,
  };
}
function configured(
  input: ActionsTargetCyclesInputV1,
  repository: MatrixCellGrantV1["cell"]["repository"],
) {
  const config = input.configs.find((entry) =>
    entry.repository.owner === repository.owner &&
    entry.repository.name === repository.name &&
    entry.repository.installationId === repository.installationId
  );
  if (config === undefined) {
    throw new Error("matrix grant repository is not configured");
  }
  return config;
}
async function readPlan(
  root: string,
  expectedDigest: string,
): Promise<MatrixPlanV1> {
  const path = root + "/plan.json";
  const info = await Deno.lstat(path);
  if (!info.isFile || info.isSymlink || info.size > MAX_MATRIX_ARTIFACT_BYTES) {
    throw new Error("matrix plan file is invalid");
  }
  const parsed = tryParseMatrixPlanV1(
    JSON.parse(await Deno.readTextFile(path)),
  );
  if (!parsed.ok || await matrixDigestV1(parsed.value) !== expectedDigest) {
    throw new Error("matrix plan does not match the trusted native digest");
  }
  return parsed.value;
}
async function writeResult(
  root: string,
  result: MatrixCellResultV1,
): Promise<void> {
  await Deno.mkdir(root, { recursive: true, mode: 0o700 });
  const bytes = canonicalStringify(result) + "\n";
  if (new TextEncoder().encode(bytes).length > MAX_MATRIX_ARTIFACT_BYTES) {
    throw new Error("matrix result is oversized");
  }
  await Deno.writeTextFile(root + "/result.json", bytes, { mode: 0o600 });
  console.log(JSON.stringify({
    kind: "sentinel_matrix_cell",
    run: result.run,
    runtimeSha: result.runtimeSha,
    generation: result.generation,
    cellId: result.cellId,
    reservationId: result.reservationId,
    resultDigest: await matrixDigestV1(result),
    bundleDigest: result.bundle?.digest ?? null,
    status: result.status,
  }));
}
function disabledResult(
  grant: MatrixCellGrantV1,
  now: number,
): MatrixCellResultV1 {
  return {
    version: "v1",
    kind: "matrix_cell_result",
    waveId: grant.waveId,
    cellId: grant.cell.cellId,
    taskId: grant.cell.taskId,
    repository: grant.cell.repository,
    run: grant.run,
    runtimeSha: grant.cell.runtimeSha,
    generation: grant.cell.generation,
    reservationId: grant.cell.reservationId,
    intentKey: grant.cell.intentKey,
    requestDigest: grant.cell.requestDigest,
    status: "not_started",
    receipt: null,
    bundle: null,
    detail: "saved execution permits deterministic verification only",
    completedAt: now,
  };
}
/** This is the production composition invoked by import.meta.main below. */
export async function runActionsMatrixHost(
  deps: ActionsMatrixHostDepsV1 = {},
): Promise<
  (MatrixPlanReportV1 & { planDigest: string }) | MatrixCellResultV1
> {
  const job = deps.env === undefined
    ? Deno.env.get("GITHUB_JOB")
    : deps.env.GITHUB_JOB;
  if (job !== "matrix_plan" && job !== "matrix_cell") {
    throw new Error("matrix executable requires its native job identity");
  }
  const carrier = job === "matrix_cell"
    ? parseCarrier(deps.carrier ?? await readMatrixNativeCarrier(true), true)
    : null;
  let result:
    | (MatrixPlanReportV1 & { planDigest: string })
    | MatrixCellResultV1
    | null = null;
  await runActionsRepairHost({
    ...deps,
    job,
    runTargetCycles: async (input) => {
      const host = hostOf(input);
      if (job === "matrix_plan") {
        // Actual intake and lifecycle reconciliation with ZERO implementation/review starts.
        const cycles = await runActionsTargetCycles({
          ...input,
          modelStartsEnabled: false,
          externalImplementations: true,
        });
        const configs = input.configs.filter((config) =>
          cycles.addressed.includes(
            config.repository.owner + "/" + config.repository.name,
          )
        );
        const first = configs[0];
        if (first === undefined) {
          throw new Error("matrix planner addressed no configured target");
        }
        const pooled = { ...input, configs };
        result = await runMatrixPlanEntrypoint({
          deps: targetDeps(pooled, first),
          options: {
            waveId: host.execution.id,
            run: host.run,
            runtimeSha: input.controllerSha,
            generation: host.execution.generation,
            deadline: input.deadline,
            plannedAt: input.clock.now(),
            modelStartsEnabled: input.modelStartsEnabled,
            githubForRepository: (repository) =>
              pooled.composeGithub(configured(pooled, repository)),
          },
          planPath: host.artifactRoot + "/plan.json",
        });
        const planned = result;
        const include = planned.plan.cells.map((cell) => ({
          cellId: cell.cellId,
          planDigest: planned.planDigest,
        }));
        const output = deps.env === undefined
          ? Deno.env.get("GITHUB_OUTPUT")
          : deps.env.GITHUB_OUTPUT;
        if (output === undefined || output.length === 0) {
          throw new Error("native matrix planner output is unavailable");
        }
        await Deno.writeTextFile(
          output,
          "matrix=" + JSON.stringify({ include }) + "\nplanDigest=" +
            result.planDigest + "\nhasCells=" + String(include.length > 0) +
            "\n",
          { append: true },
        );
        console.log(JSON.stringify({
          kind: "sentinel_matrix_plan",
          waveId: result.plan.waveId,
          run: host.run,
          runtimeSha: input.controllerSha,
          generation: host.execution.generation,
          planDigest: result.planDigest,
          prepared: result.prepared,
        }));
        return cycles;
      }
      if (carrier === null) {
        throw new Error("matrix cell lacks native selection");
      }
      const plan = await readPlan(host.artifactRoot, carrier.planDigest);
      if (
        plan.run.runId !== host.run.runId ||
        plan.run.runAttempt !== host.run.runAttempt ||
        plan.run.launcherSha !== host.run.launcherSha
      ) throw new Error("matrix plan belongs to another native execution");
      const cell = plan.cells.find((entry) => entry.cellId === carrier.cellId);
      if (cell === undefined) {
        throw new Error("native matrix cell is absent from its plan");
      }
      const grant: MatrixCellGrantV1 = {
        waveId: plan.waveId,
        run: plan.run,
        cell,
      };
      if (
        cell.runtimeSha !== input.controllerSha ||
        cell.generation !== host.execution.generation
      ) throw new Error("matrix cell runtime identity is stale");
      const config = configured(input, cell.repository);
      if (!input.modelStartsEnabled) {
        result = disabledResult(grant, input.clock.now());
      } else {
        await input.prepareTarget?.(config);
        const github = input.composeGithub(config);
        result = await runMatrixCell(
          {
            clock: input.clock,
            bounds: createRunBounds(targetDeps(input, config), {
              deadline: Math.min(
                input.deadline,
                childRunDeadlineV1(host.execution.createdAt),
              ),
              runStartedAt: host.execution.createdAt,
              modelStartsEnabled: input.modelStartsEnabled,
            }),
            sessionBound: config.sessionBound,
            state: {
              readRepair: () => input.state.readRepair(),
              readRelease: () => input.state.readRelease(),
            },
            github: { readIssue: (number) => github.readIssue(number) },
            model: input.model,
            bundle: createGitBundleExporter({
              repositoryDir: host.sourcePathFor(config),
              outputDir: host.artifactRoot,
            }),
          },
          grant,
          {
            run: host.run,
            runtimeSha: input.controllerSha,
            generation: host.execution.generation,
          },
          input.clock.now(),
        );
      }
      await writeResult(host.artifactRoot, result);
      return {
        outcome: { status: "idle", detail: "matrix cell settled" },
        addressed: [config.repository.owner + "/" + config.repository.name],
        skipped: [],
        failed: [],
      };
    },
  });
  if (result === null) throw new Error("matrix executable produced no result");
  return result;
}
async function transportFor(
  input: ActionsTargetCyclesInputV1,
  injected?: MatrixArtifactTransportV1,
): Promise<MatrixArtifactTransportV1> {
  if (injected !== undefined) return injected;
  return await hostOf(input).createArtifactTransport();
}
/** Authenticating/importing receipts precedes ordinary publication/review/delivery. */
export async function runActionsMatrixAggregateCycles(
  input: ActionsTargetCyclesInputV1,
  injectedTransport?: MatrixArtifactTransportV1,
  carrier?: MatrixNativeCarrierV1,
): Promise<ActionsTargetCyclesResultV1> {
  const host = hostOf(input);
  const read = await input.state.readRepair();
  if (!read.ok || read.value.status !== "found") {
    throw new Error("matrix aggregate cannot read authoritative state");
  }
  const requests = read.value.snapshot.work.flatMap((record) => {
    const intent = record.intent;
    if (
      (intent?.kind !== "implementation" &&
        intent?.kind !== "candidate_preservation") ||
      intent.requestId === null
    ) {
      return [];
    }
    return [{
      taskId: record.id,
      repository: record.repository,
      reservationId: intent.requestId,
      intentKey: intent.key,
      expectedBase: record.target.base,
      attempt: record.counters.attempts,
    }];
  });
  const transport = await transportFor(input, injectedTransport);
  const waves = await transport.recover({
    requests,
    runtimeSha: input.controllerSha,
    launcherSha: host.run.launcherSha,
  });
  for (const wave of waves) {
    if (
      await matrixDigestV1(wave.plan) !== wave.planDigest ||
      wave.plan.run.runId !== wave.provenance.run.runId ||
      wave.plan.run.runAttempt !== wave.provenance.run.runAttempt ||
      wave.plan.run.launcherSha !== wave.provenance.run.launcherSha ||
      !Number.isSafeInteger(wave.provenance.plannerJobId) ||
      wave.provenance.plannerJobId <= 0
    ) {
      throw new Error("matrix artifact provenance is inconsistent");
    }
    if (
      carrier !== undefined && wave.plan.run.runId === host.run.runId &&
      wave.plan.run.runAttempt === host.run.runAttempt &&
      wave.planDigest !== carrier.planDigest
    ) {
      throw new Error(
        "matrix aggregate plan differs from native planner output",
      );
    }
    for (const config of input.configs) {
      const cells = wave.plan.cells.filter((cell) =>
        cell.repository.owner === config.repository.owner &&
        cell.repository.name === config.repository.name &&
        cell.repository.installationId === config.repository.installationId
      );
      if (cells.length === 0) continue;
      await input.prepareTarget?.(config);
      const report = await ingestMatrixResults(
        targetDeps(input, config),
        { ...wave.plan, cells },
        wave.results.filter((entry) =>
          cells.some((cell) => cell.cellId === entry.cellId)
        ),
        {
          deadline: input.deadline,
          expectedProvider: host.expectedProvider,
          bundleImporter: createGitBundleImporter({
            repositoryDir: host.sourcePathFor(config),
            bundlesDir: wave.bundlesDir,
          }),
        },
      );
      console.log(
        JSON.stringify({ kind: "sentinel_matrix_ingest", ...report }),
      );
    }
  }
  // Missing/unavailable cell artifacts stay charged and unresolved. Reviews and
  // delivery retain the real ordinary lifecycle; implementation never falls back.
  return await runActionsTargetCycles({
    ...input,
    modelStartsEnabled: carrier === undefined
      ? false
      : input.modelStartsEnabled,
    externalImplementations: true,
  });
}
if (import.meta.main) {
  await runActionsMatrixHost();
}
